package com.netteans.example.mybatis.dao.mapper;

import com.netteans.example.mybatis.dao.model.ExampleMessage;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ExampleMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_message
     *
     * @mbggenerated
     */
    @Delete({
        "delete from example_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_message
     *
     * @mbggenerated
     */
    @Insert({
        "insert into example_message (id, type, ",
        "message_id, message_body)",
        "values (#{id,jdbcType=INTEGER}, #{type,jdbcType=SMALLINT}, ",
        "#{messageId,jdbcType=VARCHAR}, #{messageBody,jdbcType=VARCHAR})"
    })
    int insert(ExampleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_message
     *
     * @mbggenerated
     */
    int insertSelective(ExampleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_message
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, type, message_id, message_body",
        "from example_message",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ExampleMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExampleMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table example_message
     *
     * @mbggenerated
     */
    @Update({
        "update example_message",
        "set type = #{type,jdbcType=SMALLINT},",
          "message_id = #{messageId,jdbcType=VARCHAR},",
          "message_body = #{messageBody,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ExampleMessage record);
}