# Spring boot application
spring.application.name: dubbo-registry-zookeeper-provider-sample
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service

embedded.zookeeper.port: 2181
dubbo:
  scan.base-packages: com.netteans.dubbo.example.service

  # Dubbo Application
  ## The default value of dubbo.application.name is ${spring.application.name}
  ## dubbo.application.name=${spring.application.name}

  # Dubbo Protocol
  protocol:
    name: dubbo
    ## Random port
    port: -1

  ## Dubbo Registry
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbobk.cache

## DemoService version
demo.service.version: 1.0.0