server.port: 8080

spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mybatis_example?useUnicode=true&characterEncoding=utf-8
  username: tester
  password: 1234
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis-mapper/*.xml #mapper.xml location
  configuration.jdbc-type-for-null: 'null'
