#必须有bootstrap.yml,否则不能加载spring cloud backend server 配置
server:
  port: 8808
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
        isolation:
          thread:
            timeoutInSeconds: 10
management:
  endpoints:
    web:
      exposure:
          include: hystrix.stream, info, health, turbine.stream