#必须有bootstrap.yml,否则不能加载spring cloud config server 配置

feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInSeconds: 10
management:
  endpoints:
    web:
      exposure:
          include: hystrix.stream, info, health