package com.netteans.example.mybatis.dao.model;

public class ExampleMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_message.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_message.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_message.message_id
     *
     * @mbggenerated
     */
    private String messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column example_message.message_body
     *
     * @mbggenerated
     */
    private String messageBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_message.id
     *
     * @return the value of example_message.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_message.id
     *
     * @param id the value for example_message.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_message.type
     *
     * @return the value of example_message.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_message.type
     *
     * @param type the value for example_message.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_message.message_id
     *
     * @return the value of example_message.message_id
     *
     * @mbggenerated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_message.message_id
     *
     * @param messageId the value for example_message.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column example_message.message_body
     *
     * @return the value of example_message.message_body
     *
     * @mbggenerated
     */
    public String getMessageBody() {
        return messageBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column example_message.message_body
     *
     * @param messageBody the value for example_message.message_body
     *
     * @mbggenerated
     */
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody == null ? null : messageBody.trim();
    }
}